# Nom de l'application
spring:
  application:
    name: gestionEmployerBackend

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:gestion_employes}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  api:
    prefix: /api/v1
  secret-key: ${APP_SECRET_KEY}
  expiration-time: 900000
